In [1]:
# imports
from laminatelib import laminateStiffnessMatrix
import numpy as np

In [2]:
# Material
cfrp = {"name": "CFRP", "units": "MPa-mm-Mg", "type": "UD", "fiber": "Carbon",
        "Vf": 0.55, "rho": 1600E-12,
        "description": "Vacuum infused UD carbon (T300)",  
        "E1": 130000, "E2": 10000, "E3": 10000, 
        "v12": 0.28, "v13": 0.28, "v23": 0.5, 
        "G12": 4500, "G13": 4500, "G23": 3500, 
        "a1": -0.5e-06, "a2": 3.0e-05, "a3": 3.0e-05, 
        "XT": 1400, "YT": 30, "ZT": 30,
        "XC":  900, "YC": 120, "ZC": 120,
        "S12": 60, "S13": 60, "S23": 30,
        "f12":-0.5, "f13":-0.5, "f23":-0.5}

In [4]:
# Layup
layup  = [ 
        {'mat':cfrp , 'ori':  0  , 'thi':1},
        {'mat':cfrp , 'ori': 90  , 'thi':1},
        {'mat':cfrp , 'ori':  0  , 'thi':1}, 
        {'mat':cfrp , 'ori': 90  , 'thi':1},
]
layup2  = [ 
        {'mat':cfrp , 'ori': 90  , 'thi':1},
        {'mat':cfrp , 'ori':  0  , 'thi':1},
        {'mat':cfrp , 'ori': 90  , 'thi':1},
        {'mat':cfrp , 'ori':  0  , 'thi':1},
]

# Calculate effective stress
ABD = laminateStiffnessMatrix(layup)
print(np.round(ABD), '\n')
ABD = laminateStiffnessMatrix(layup2)
print(np.round(ABD))

[[ 281699.   11268.       0. -120728.      -0.       0.]
 [  11268.  281699.       0.       0.  120728.       0.]
 [      0.       0.   18000.       0.       0.       0.]
 [-120728.      -0.       0.  375598.   15024.       0.]
 [      0.  120728.       0.   15024.  375598.       0.]
 [      0.       0.       0.       0.       0.   24000.]] 

[[ 281699.   11268.       0.  120728.       0.      -0.]
 [  11268.  281699.       0.      -0. -120728.      -0.]
 [      0.       0.   18000.      -0.      -0.       0.]
 [ 120728.       0.      -0.  375598.   15024.       0.]
 [     -0. -120728.      -0.   15024.  375598.       0.]
 [     -0.      -0.       0.       0.       0.   24000.]]
